import { create } from '../class';

describe('Long', () => {
  const i18n = create(
    () => ({
      '10': 'Capital — overall grouping of all capital accounts',
      '11': 'Reserves — retained profits left at the disposal of the entity',
      '12': 'Retained earnings / accumulated losses — profit or loss carried forward from prior periods',
      '13': 'Net income/loss for the period — the bottom-line result',
      '14': 'Investment grants — non-repayable funds received to finance fixed assets or long-term activities',
      '15': 'Regulated provisions and equivalent funds — fiscal/regulatory appropriations (e.g. accelerated depreciation, reinvestment reserves)',
      '16': 'Borrowings and similar liabilities — long-term financial debt (bonds, bank loans, State advances, deposits, etc.)',
      '17': 'Finance lease liabilities and similar contracts — long-term lease obligations',
      '18': 'Debts related to equity investments and inter-branch liaison accounts',
      '19': 'Financial provisions for risks and charges — long-term contingency provisions (>1 year)',
      '20': 'Deferred charges — capitalised start-up, restructuring and similar costs',
      '21': 'Intangible assets',
      '22': 'Land',
      '23': 'Buildings, technical installations and fittings',
      '24': 'Equipment and machinery',
      '25': 'Advances and deposits paid on fixed assets (prepayments to suppliers of non-current assets)',
      '26': 'Equity investments (shareholdings) — strategic long-term investments',
      '27': 'Other long-term financial assets',
      '28': 'Accumulated depreciation on fixed assets (contra account)',
      '29': 'Impairment provisions on fixed assets (contra account)',
      '31': 'Merchandise / goods for resale',
      '32': 'Raw materials and related supplies',
      '33': 'Other supplies and consumables',
      '34': 'Work in progress — manufactured products',
      '35': 'Services in progress (work performed but not yet billed)',
      '36': 'Finished goods',
      '37': 'Semi-finished goods and by-products',
      '38': 'Goods in transit, on consignment or in storage',
      '39': 'Impairment provisions on inventories',
      '40': 'Suppliers and related accounts',
      '41': 'Customers and related accounts',
      '42': 'Employee-related accounts (payroll payables and receivables)',
      '43': 'Social security and social organisations',
      '44': 'State and public authorities — tax and other fiscal accounts',
      '45': 'International organisations',
      '46': 'Shareholders, partners and group companies',
      '47': 'Miscellaneous debtors and creditors',
      '48': 'Non-ordinary activity receivables and payables (capital account items)',
      '49': 'Impairment provisions and provisioned risks on third-party accounts',
      '50': 'Short-term investment securities (marketable securities)',
      '51': 'Values pending collection (bills and cheques not yet cleared)',
      '52': 'Bank accounts (current / demand accounts)',
      '53': 'Financial institutions and equivalents (non-bank)',
      '54': 'Treasury instruments (derivative financial instruments)',
      '56': 'Bank overdrafts, short-term credit facilities and discounting',
      '57': 'Cash on hand (petty cash)',
      '58': 'Petty cash advances, letters of credit and internal transfers',
      '59': 'Impairment provisions and provisioned risks on treasury accounts',
      '60': 'Purchases and inventory movements',
      '61': 'Transport expenses',
      '62': 'External services — group A (facilities and contracted services)',
      '63': 'External services — group B (professional and administrative services)',
      '64': 'Taxes, duties and levies (excluding income tax)',
      '65': 'Other operating charges',
      '66': 'Employee costs — wages, salaries and related charges',
      '67': 'Finance costs and similar charges',
      '68': 'Depreciation and amortisation charges',
      '69': 'Provisions charged (increase in provisions)',
      '70': 'Revenue from sales of goods and services',
      '71': 'Operating grants (to subsidise operations)',
      '72': 'Own-work capitalised (assets produced for own use)',
      '73': 'Change in inventories of produced goods and services',
      '75': 'Other operating income',
      '77': 'Financial income and similar revenues',
      '78': 'Charge transfers (costs recharged or reclassified)',
      '79': 'Reversals of long-term provisions',
      '81': 'Net book value of fixed assets disposed of (HAO charge)',
      '82': 'Proceeds from disposal of fixed assets (HAO income)',
      '83': 'Extraordinary / non-ordinary activity charges (HAO expenses)',
      '84': 'Extraordinary / non-ordinary activity income (HAO revenues)',
      '85': 'HAO depreciation, amortisation and provision charges (extraordinary)',
      '86': 'Reversals of HAO provisions and amortisation (extraordinary)',
      '87': 'Employee profit-sharing charges',
      '88': 'Balancing grants — grants to compensate operating losses (subsidy)',
      '89': 'Income tax (corporate tax on profit)',
      '90': 'Off-balance-sheet commitments — received and given',
      '91': 'Counterpart accounts for off-balance-sheet commitments (to balance accounts 90)',
      '92': 'Reflected / mirror accounts — reclassification of general ledger balances into management accounting',
      '93': 'Reclassification accounts — allocation of costs and revenues to cost centres',
      '94': 'Cost accounts — accumulation of costs by product, activity or cost centre',
      '95': 'Management accounting stock accounts — valued at standard or actual cost',
      '96': 'Variance accounts — differences between standard and actual costs',
      '97': 'Accounts for differences between financial and management accounting treatment',
      '98': 'Management accounting result accounts — analytical profit and loss',
      '99': 'Internal liaison accounts — transfers between management and financial accounting',
      '101': 'Share capital — value of contributions made by shareholders',
      '102':
        'Endowment capital — funds allocated by a public authority to a public entity',
      '103':
        'Sole-trader personal capital — owner equity in an individual enterprise',
      '104':
        "Owner's current account — tracks the sole trader's personal drawings and contributions during the year",
      '105':
        'Share premiums — excess of issue/merger/contribution price over nominal value',
      '106':
        'Revaluation surplus — increase in asset values recognised via revaluation',
      '109':
        'Shareholders — subscribed capital not yet called (contra to 1011); shown as a deduction from equity',
      '111':
        'Legal reserve — mandatory appropriation of at least 10% of annual profit',
      '112':
        'Statutory or contractual reserves — required by the articles of association',
      '113':
        'Regulated reserves — created under specific legal or tax provisions',
      '118': 'Other reserves — freely distributable reserves',
      '121': 'Retained earnings (credit balance — accumulated profits)',
      '129': 'Accumulated losses (debit balance — unabsorbed losses)',
      '130':
        'Profit/loss pending appropriation — result awaiting the general assembly decision',
      '131': 'Net profit for the period',
      '132':
        'Gross margin — difference between net sales and cost of goods sold',
      '133': 'Value added — gross margin less other external charges',
      '134': 'Gross operating surplus (EBITDA equivalent)',
      '135':
        'Operating result — profit or loss from ordinary operating activities',
      '136': 'Financial result — net income from financial activities',
      '137': 'Result from ordinary activities (operating + financial)',
      '138': 'Result from extraordinary/non-ordinary activities (HAO)',
      '139': 'Net loss for the period',
      '141': 'Equipment grants — category A (State and local authorities)',
      '142': 'Equipment grants — category B',
      '148': 'Other investment grants',
      '151': 'Accelerated (tax-driven) depreciation provisions',
      '152': 'Capital gains to be reinvested — tax deferral provision',
      '153': 'Regulated funds',
      '154': 'Special revaluation provision (fiscal neutrality provision)',
      '155':
        'Regulated provisions relating to fixed assets (e.g. mining/oil field reconstitution)',
      '156': 'Regulated provisions relating to inventories',
      '157': 'Investment provisions',
      '158': 'Other regulated provisions and funds',
      '161': 'Bond loans',
      '162': 'Loans and debts from credit institutions (banks)',
      '163': 'Advances received from the State',
      '164': 'Advances received and blocked current accounts',
      '165': 'Deposits and sureties received',
      '166': 'Accrued interest on long-term borrowings',
      '167': 'Advances subject to special conditions (conditional grants)',
      '168': 'Other borrowings and debts',
      '172': 'Finance lease liabilities — real estate (property)',
      '173': 'Finance lease liabilities — movable assets (equipment)',
      '176': 'Accrued interest on finance lease liabilities',
      '178': 'Finance lease liabilities — other contract types',
      '181': 'Debts related to equity participations',
      '182': 'Debts related to joint ventures (sociétés en participation)',
      '183': 'Accrued interest on participation-related debts',
      '184': 'Blocked permanent accounts of branches and subsidiaries',
      '185': 'Non-blocked permanent accounts of branches and subsidiaries',
      '186': 'Inter-branch liaison accounts — expense transfers',
      '187': 'Inter-branch liaison accounts — revenue transfers',
      '188': 'Liaison accounts for joint venture entities',
      '191': 'Provisions for litigation and legal disputes',
      '192': 'Provisions for warranties given to customers',
      '193': 'Provisions for losses on long-term contracts',
      '194': 'Provisions for foreign exchange losses',
      '195': 'Provisions for taxes',
      '196':
        'Provisions for pensions and similar post-employment obligations',
      '197':
        'Provisions for charges to be spread over several accounting periods',
      '198': 'Other financial provisions for risks and charges',
      '201': 'Start-up / formation costs',
      '202': 'Charges to be spread over several accounting periods',
      '206':
        'Bond redemption premiums — excess of redemption value over issue value',
      '211': 'Research and development costs (capitalised)',
      '212': 'Patents, licences, concessions and similar rights',
      '213': 'Software (computer programs)',
      '214': 'Trademarks and brand names',
      '215': 'Goodwill (business value / fonds de commerce)',
      '216': 'Leasehold rights (droit au bail)',
      '217': 'Creative / artistic investments',
      '218': 'Other intangible rights and values',
      '219': 'Intangible assets under construction / development',
      '221': 'Agricultural and forestry land',
      '222': 'Bare / undeveloped land',
      '223': 'Land with buildings',
      '224': 'Land development works',
      '225': 'Mineral / quarry land (extractive sites)',
      '226': 'Developed / improved land',
      '227': 'Land held under concession',
      '228': 'Other land',
      '229': 'Land improvements under construction',
      '231':
        'Industrial, agricultural, administrative and commercial buildings on own land',
      '232':
        'Industrial, agricultural, administrative and commercial buildings on third-party land',
      '233': 'Infrastructure works',
      '234': 'Technical installations',
      '235': 'Office fit-outs and fittings',
      '237':
        'Industrial, agricultural and commercial buildings held under concession',
      '238': 'Other installations and fittings',
      '239': 'Buildings and installations under construction',
      '241': 'Industrial and commercial machinery and tools',
      '242': 'Agricultural equipment and tools',
      '243':
        'Returnable and individually identifiable packaging equipment',
      '244': 'Office equipment and furniture',
      '245': 'Transport equipment and vehicles',
      '246': 'Biological assets — animals and agricultural plantations',
      '247': 'Equipment fittings and improvements',
      '248': 'Other equipment',
      '249': 'Equipment under construction or acquisition',
      '251': 'Advances paid on intangible assets',
      '252': 'Advances paid on tangible assets',
      '261': 'Equity investments in subsidiaries (exclusive control)',
      '262': 'Equity investments in jointly controlled entities',
      '263': 'Equity investments in associates (significant influence)',
      '265': 'Interests in professional organisations',
      '266': 'Interests in Economic Interest Groups (EIG / GIE)',
      '268': 'Other equity investment securities',
      '271': 'Long-term loans and non-trade receivables',
      '272': 'Loans to employees',
      '273': 'Long-term receivables from the State',
      '274': 'Long-term investment securities (non-controlling)',
      '275': 'Deposits and sureties paid (long-term)',
      '276': 'Accrued interest on long-term financial assets',
      '277':
        'Receivables related to equity investments and advances to GIE',
      '278': 'Miscellaneous long-term financial assets',
      '281': 'Accumulated depreciation — intangible assets',
      '282':
        'Accumulated depreciation — land (extractive/development sites)',
      '283':
        'Accumulated depreciation — buildings, installations and fittings',
      '284': 'Accumulated depreciation — equipment',
      '291': 'Impairment provisions — intangible assets',
      '292': 'Impairment provisions — land',
      '293': 'Impairment provisions — buildings and installations',
      '294': 'Impairment provisions — equipment',
      '295': 'Impairment provisions — advances on fixed assets',
      '296': 'Impairment provisions — equity investments',
      '297': 'Impairment provisions — other long-term financial assets',
      '311': 'Merchandise — category A',
      '312': 'Merchandise — category B',
      '318': 'Merchandise held outside ordinary activities (HAO)',
      '321': 'Raw materials — category A',
      '322': 'Raw materials — category B',
      '323': 'Supplies — categories A and B',
      '331': 'Consumable materials',
      '332': 'Workshop and factory supplies',
      '333': 'Store/warehouse supplies',
      '334': 'Office supplies',
      '335': 'Packaging materials',
      '338': 'Other materials and supplies',
      '341': 'Products in progress',
      '342': 'Work in progress — construction/services',
      '343': 'Semi-finished products in progress',
      '344': 'By-products and waste in progress',
      '351': 'Studies / consulting projects in progress',
      '352': 'Service contracts in progress',
      '361': 'Finished goods — category A',
      '362': 'Finished goods — category B',
      '371': 'Semi-finished / intermediate products',
      '372': 'By-products, waste and scrap',
      '381': 'Merchandise in transit',
      '382': 'Raw materials in transit',
      '383': 'Other supplies in transit',
      '386': 'Finished goods in transit',
      '387': 'Stock on consignment or in storage',
      '388': 'Stock arising from decommissioned or scrapped fixed assets',
      '391': 'Impairment — merchandise stocks',
      '392': 'Impairment — raw materials and related supplies',
      '393': 'Impairment — other supply stocks',
      '394': 'Impairment — work in progress (products)',
      '395': 'Impairment — services in progress',
      '396': 'Impairment — finished goods',
      '397': 'Impairment — semi-finished goods and by-products',
      '398':
        'Impairment — stocks in transit, on consignment or in storage',
      '401': 'Suppliers — open account trade payables',
      '402': 'Suppliers — bills payable (promissory notes / drafts)',
      '408':
        'Suppliers — uninvoiced goods and services (accrued payables)',
      '409': 'Suppliers — debit balances (prepayments and returns)',
      '411': 'Trade receivables — customers',
      '412':
        'Customers — bills receivable (notes and drafts in portfolio)',
      '414': 'Receivables from asset disposals',
      '415': 'Customer bills discounted but not yet due',
      '416': 'Disputed or doubtful customer receivables',
      '418': 'Customers — accrued income (invoices to be raised)',
      '419': 'Customers — credit balances (advances and returns)',
      '421': 'Employee advances and salary advances',
      '422': 'Salaries and wages payable',
      '423': 'Wage garnishments and attachments',
      '424': 'Employee welfare benefits (company-managed)',
      '425': 'Employee representatives (works council, unions)',
      '426': 'Employee profit-sharing payable',
      '427': 'Employee deposits held',
      '428': 'Employee-related accrued liabilities and receivables',
      '431': 'Social security contributions payable',
      '432': 'Supplementary pension fund contributions',
      '433': 'Other social organisations',
      '438': 'Accrued social charges and receivables',
      '441': 'Corporate income tax payable / recoverable',
      '442': 'State — other taxes and duties',
      '443': 'Output VAT (billed/charged to customers)',
      '444': 'VAT payable or VAT credit balance',
      '445': 'Input VAT recoverable',
      '446': 'State — other turnover taxes',
      '447': 'State — taxes withheld at source (withholding taxes)',
      '448': 'State — accrued tax liabilities and receivables',
      '449': 'State — miscellaneous receivables and payables',
      '451': 'Transactions with African organisations',
      '452': 'Transactions with other international organisations',
      '458':
        'International organisations — endowment funds and grants receivable',
      '461': 'Shareholders — capital transactions',
      '462': 'Shareholders — current accounts (partners loan accounts)',
      '463': 'Partners — joint venture transactions',
      '465': 'Dividends payable to shareholders',
      '466': 'Group companies — current accounts',
      '467': 'Shareholders — amount still due on called capital',
      '471': 'Suspense accounts (temporary holding accounts)',
      '472': 'Remaining payments due on partially paid-up securities',
      '474':
        'Periodic allocation of income and expenses (accruals and deferrals)',
      '475':
        'Receivables on work not yet billable (contract work in progress)',
      '476': 'Prepaid expenses (deferred charges)',
      '477': 'Deferred income (deferred revenue)',
      '478':
        'Translation differences — asset (unrealised exchange losses)',
      '479':
        'Translation differences — liability (unrealised exchange gains)',
      '481': 'Suppliers of fixed assets (capital expenditure payables)',
      '482': 'Capital expenditure suppliers — bills payable',
      '483': 'Payables on acquisition of investment securities',
      '484': 'Other non-ordinary activity payables',
      '485': 'Receivables from fixed asset disposals',
      '486': 'Receivables from disposal of investment securities',
      '488': 'Other non-ordinary activity receivables',
      '490': 'Impairment on supplier accounts',
      '491': 'Impairment on customer receivables',
      '492': 'Impairment on employee receivables',
      '493': 'Impairment on social organisation receivables',
      '494': 'Impairment on State and public authority receivables',
      '495': 'Impairment on international organisation receivables',
      '496': 'Impairment on shareholder and group receivables',
      '497': 'Impairment on miscellaneous debtor accounts',
      '498': 'Impairment on non-ordinary activity receivables',
      '499': 'Short-term provisions for risks',
      '501': 'Treasury bills and short-term certificates of deposit',
      '502': 'Shares held as short-term investments',
      '503': 'Bonds held as short-term investments',
      '504': 'Subscription warrants',
      '505': 'Negotiable securities from outside the UEMOA region',
      '506': 'Accrued interest on short-term investment securities',
      '508': 'Other equivalent marketable values',
      '511': 'Bills of exchange to collect (held in portfolio)',
      '512': 'Bills submitted to bank for collection (in transit)',
      '513': 'Cheques received but not yet deposited',
      '514': 'Cheques deposited but not yet cleared',
      '515': 'Credit card receipts pending settlement',
      '518': 'Other values pending collection',
      '521': 'Local bank accounts (same country)',
      '522': 'Bank accounts in other UEMOA member states',
      '523': 'Bank accounts in other CFA franc zone states',
      '524': 'Bank accounts outside the monetary zone',
      '526': 'Accrued interest on bank accounts',
      '531': 'Postal cheque accounts (CCP)',
      '532': 'Treasury accounts (government deposits)',
      '533': 'Securities management and brokerage firms (SGI)',
      '536': 'Accrued interest on financial institution accounts',
      '538': 'Other financial organisations',
      '541': 'Interest rate options',
      '542': 'Foreign exchange options',
      '543': 'Equity market rate options',
      '544': 'Futures and forward market instruments',
      '545': 'Gold and precious metal holdings (treasury)',
      '561': 'Short-term bank credit facilities (revolving credit)',
      '564': 'Discounting of seasonal / campaign credit facilities',
      '565': 'Ordinary bill discounting facilities',
      '566': 'Accrued interest on short-term bank credit and discounting',
      '571': 'Head office cash',
      '572': 'Branch A cash',
      '573': 'Branch B cash',
      '581': 'Imprest petty cash funds',
      '582': 'Letters of credit',
      '585': 'Internal fund transfers in transit',
      '588': 'Other internal transfers',
      '590': 'Impairment on short-term investment securities',
      '591': 'Impairment on bills and values pending collection',
      '592': 'Impairment on bank accounts',
      '593': 'Impairment on financial institution accounts',
      '594': 'Impairment on treasury instrument accounts',
      '599': 'Short-term provisions for financial risks',
      '601': 'Purchases of merchandise for resale',
      '602': 'Purchases of raw materials and related supplies',
      '603':
        'Change in inventories of purchased goods (merchandise and raw materials)',
      '604':
        'Purchases of consumable materials and supplies (held in stock)',
      '605': 'Other purchases (non-stock items and services)',
      '608': 'Purchases of packaging materials',
      '611': 'Inbound freight and transport on purchases',
      '612': 'Outbound freight and transport on sales',
      '613': 'Transport on behalf of third parties',
      '614': 'Employee transport and commuting expenses',
      '616': 'Mail and parcel delivery expenses',
      '618': 'Other transport expenses',
      '621': 'General subcontracting expenses',
      '622': 'Rent and occupancy charges',
      '623': 'Finance lease rentals and similar contract payments',
      '624': 'Maintenance, repairs and upkeep expenses',
      '625': 'Insurance premiums',
      '626': 'Studies, research and documentation expenses',
      '627': 'Advertising, publications and public relations',
      '628': 'Telecommunications expenses',
      '631': 'Bank charges and fees',
      '632': 'Fees paid to intermediaries and advisors',
      '633': 'Staff training and development expenses',
      '634':
        'Royalties for patents, licences, software and similar rights',
      '635': 'Membership dues and professional contributions',
      '637': 'Fees for temporary and seconded external staff',
      '638': 'Other external charges',
      '641': 'Direct taxes and duties',
      '645': 'Indirect taxes and duties',
      '646': 'Registration duties and stamp taxes',
      '647': 'Tax penalties and fines',
      '648': 'Other taxes and levies',
      '651': 'Losses on write-off of customer and other receivables',
      '652': 'Share of result on joint venture transactions',
      '653':
        'Result reversal on partial completion of multi-year contracts',
      '654':
        'Net book value of fixed assets sold in ordinary course of business',
      '658': 'Miscellaneous other charges',
      '659': 'Short-term operating risk provisions (charge)',
      '661': 'Direct remuneration paid to local (national) staff',
      '662': 'Direct remuneration paid to expatriate staff',
      '663': 'Lump-sum allowances paid to staff',
      '664': 'Employer social security and social charges',
      '666': "Sole trader's own remuneration and social charges",
      '667': 'Cost transfer for external staff (temporary and seconded)',
      '668': 'Other employee-related social expenses',
      '671': 'Interest expense on borrowings',
      '672': 'Finance charges within lease rentals',
      '673': 'Settlement discounts granted to customers',
      '674': 'Other interest expenses',
      '675': 'Bill discounting charges (discount on commercial paper)',
      '676': 'Foreign exchange losses',
      '677': 'Losses on disposal of short-term investment securities',
      '678': 'Losses on financial risks',
      '679': 'Financial risk provisions (charge)',
      '681': 'Operating depreciation and amortisation charges',
      '687': 'Financial depreciation charges',
      '691': 'Operating provisions charged',
      '697': 'Financial provisions charged',
      '701': 'Sales of merchandise (goods for resale)',
      '702': 'Sales of finished manufactured goods',
      '703': 'Sales of semi-finished / intermediate products',
      '704': 'Sales of by-products, waste and scrap',
      '705': 'Billed construction and works contracts',
      '706': 'Services rendered and billed',
      '707': 'Ancillary revenues and incidental income',
      '711': 'Export product subsidies',
      '712': 'Import product subsidies',
      '713': 'Price equalisation / stabilisation subsidies',
      '718': 'Other operating grants',
      '721': 'Capitalised intangible assets produced internally',
      '722': 'Capitalised tangible assets produced internally',
      '726': 'Capitalised financial assets produced internally',
      '734': 'Change in work in progress (products)',
      '735': 'Change in services in progress',
      '736': 'Change in finished goods inventory',
      '737': 'Change in semi-finished goods and by-products inventory',
      '752': 'Share of profit on joint venture transactions',
      '753':
        'Portion of profit on partial completion of multi-year contracts',
      '754':
        'Proceeds from disposal of fixed assets in the ordinary course',
      '758': 'Miscellaneous other income',
      '759': 'Reversal of short-term operating risk provisions',
      '771': 'Interest income on loans granted',
      '772': 'Dividend and participation income',
      '773': 'Settlement discounts received from suppliers',
      '774': 'Income from short-term investment securities',
      '776': 'Foreign exchange gains',
      '777': 'Gains on disposal of short-term investment securities',
      '778': 'Gains on financial risks (derivative settlements)',
      '779': 'Reversal of financial risk provisions',
      '781': 'Operating charge transfers',
      '787': 'Financial charge transfers',
      '791': 'Reversals of operating provisions',
      '797': 'Reversals of financial provisions',
      '798':
        'Reversals of amortisation (including investment grant transfers)',
      '811': 'Net book value of disposed intangible assets',
      '812': 'Net book value of disposed tangible assets',
      '816': 'Net book value of disposed financial assets',
      '821': 'Proceeds from disposal of intangible assets',
      '822': 'Proceeds from disposal of tangible assets',
      '826': 'Proceeds from disposal of financial assets',
      '831': 'Recognised HAO charges (extraordinary expenses)',
      '834': 'Losses on write-off of HAO receivables',
      '835': 'Gifts and donations made',
      '836': 'Debt waivers and write-offs granted to third parties',
      '839': 'HAO provisions charged (extraordinary risk provisions)',
      '841': 'Recognised HAO income (extraordinary revenues)',
      '845': 'Gifts and donations received',
      '846': 'Debt waivers received from third parties',
      '848': 'HAO charge transfers',
      '849': 'Reversals of HAO risk provisions',
      '851': 'Regulated provision charges (HAO)',
      '852': 'Accelerated / extraordinary depreciation charges (HAO)',
      '853': 'HAO impairment provision charges',
      '854': 'HAO risk and charge provision charges',
      '858': 'Other HAO provision charges',
      '861': 'Reversals of regulated provisions (HAO)',
      '862': 'Reversals of extraordinary depreciation (HAO)',
      '863': 'Reversals of HAO impairment provisions',
      '864': 'Reversals of HAO risk and charge provisions',
      '865':
        'Transfer of investment grants to profit (annual amortisation)',
      '868': 'Other HAO provision reversals',
      '871': 'Statutory employee profit-sharing charge',
      '874': 'Contractual employee profit-sharing charge',
      '878': 'Other employee participation charges',
      '881': 'Balancing grant from the State',
      '884': 'Balancing grant from public authorities',
      '886': 'Balancing grant from the group',
      '888': 'Balancing grant from other sources',
      '891': 'Current year corporate income tax',
      '892': 'Additional tax assessments on prior year results',
      '895':
        'Minimum flat-rate tax (IMF — applicable in some OHADA states)',
      '899': 'Tax credits and cancellations relating to prior year taxes',
      '901': 'Financing commitments obtained (credit facilities, etc.)',
      '902': 'Guarantee commitments received',
      '903': 'Reciprocal/mutual commitments obtained',
      '904': 'Other commitments obtained',
      '905': 'Financing commitments given to third parties',
      '906': 'Guarantee commitments given',
      '907': 'Reciprocal/mutual commitments given',
      '908': 'Other commitments given',
      '911': 'Counterpart — financing commitments obtained (901)',
      '915': 'Counterpart — financing commitments granted (905)',
      '1011': 'Subscribed capital, not yet called up',
      '1012': 'Subscribed capital, called up but not yet paid in',
      '1013': 'Subscribed capital, called up, paid in, not yet redeemed',
      '1014': 'Subscribed capital, called up, paid in and redeemed',
      '1018': 'Subscribed capital subject to special conditions',
      '1021': 'Initial endowment',
      '1022': 'Supplementary endowments',
      '1028': 'Other endowments',
      '1041': 'Temporary contributions by the owner',
      '1042': 'Current operating transactions with the owner',
      '1043':
        "Owner's personal remuneration, taxes and other personal expenses",
      '1047': 'Owner withdrawals of goods for personal consumption',
      '1048': 'Other owner withdrawals',
      '1051': 'Share issue premium',
      '1052': 'Contribution premium',
      '1053': 'Merger premium',
      '1054': 'Conversion premium',
      '1058': 'Other equity-related premiums',
      '1061': 'Legal revaluation surplus (mandatory revaluation)',
      '1062': 'Free revaluation surplus (voluntary revaluation)',
      '1131': 'Reserve for net long-term capital gains',
      '1133': 'Reserve arising from investment grants received',
      '1138': 'Other regulated reserves',
      '1181': 'Optional (discretionary) reserves',
      '1188': 'Miscellaneous reserves',
      '1291': 'Net loss carried forward',
      '1292': 'Loss — depreciation deemed deferred (tax treatment)',
      '1301': 'Profit pending appropriation',
      '1309': 'Loss pending appropriation',
      '1321': 'Gross margin on merchandise',
      '1322': 'Gross margin on raw materials',
      '1411': 'Investment grant from the State',
      '1412': 'Investment grant from regional authorities',
      '1413': 'Investment grant from departmental authorities',
      '1414':
        'Investment grant from municipalities and decentralised public bodies',
      '1415': 'Investment grant from state-owned or mixed enterprises',
      '1416': 'Investment grant from private companies and organisations',
      '1417': 'Investment grant from international organisations',
      '1418': 'Other investment grants',
      '1531': 'National regulated fund',
      '1532': 'Budget levy provision',
      '1551': 'Provision for reconstitution of mining and oil fields',
      '1561': 'Price increase provision (stock)',
      '1562': 'Market price fluctuation provision (stock)',
      '1611': 'Ordinary bond loans',
      '1612': 'Convertible bond loans',
      '1618': 'Other bond loans',
      '1651': 'Deposits received',
      '1652': 'Sureties (bonds) received',
      '1661': 'Accrued interest on bond loans',
      '1662': 'Accrued interest on bank loans',
      '1663': 'Accrued interest on State advances',
      '1664': 'Accrued interest on blocked advances and current accounts',
      '1665': 'Accrued interest on deposits and sureties received',
      '1667': 'Accrued interest on advances with special conditions',
      '1668': 'Accrued interest on other borrowings and debts',
      '1671': 'Advances blocked pending capital increase',
      '1672': 'Conditional advances from the State',
      '1673': 'Conditional advances from other African organisations',
      '1674': 'Conditional advances from international organisations',
      '1676': 'Concession rights payable in kind',
      '1681': 'Capitalised life annuities',
      '1682': 'Business purchase notes payable',
      '1683': 'Debts arising from borrowed securities',
      '1684': "Concessionaire's debts payable in kind",
      '1685': 'Participating loans',
      '1686': 'Employee profit-sharing liability',
      '1762': 'Accrued interest on real estate finance leases',
      '1763': 'Accrued interest on movable asset finance leases',
      '1768': 'Accrued interest on other lease contracts',
      '1811': 'Intra-group participation debts',
      '1812': 'Non-group participation debts',
      '1971': 'Provisions for major repairs and overhauls',
      '1981': 'Provisions for fines and penalties',
      '1982': 'Provisions for asset renewal (concession companies)',
      '1983': 'Self-insurance provisions',
      '1988':
        'Other miscellaneous financial provisions for risks and charges',
      '2011': 'Incorporation costs',
      '2012': 'Prospecting / survey costs',
      '2013': 'Advertising and launch costs',
      '2014': 'Pre-operating costs incurred before start of business',
      '2015':
        'Capital restructuring costs (mergers, demergers, conversions)',
      '2016': 'Stock exchange listing costs',
      '2017': 'Restructuring costs',
      '2018': 'Miscellaneous formation costs',
      '2021': 'Deferred charges',
      '2022': 'Fixed asset acquisition costs',
      '2026': 'Bond issuance costs',
      '2028': 'Charges to be spread (other)',
      '2061': 'Redemption premiums — ordinary bonds',
      '2062': 'Redemption premiums — convertible bonds',
      '2068': 'Redemption premiums — other bonds',
      '2191': 'R&D in progress',
      '2193': 'Software under development',
      '2198': 'Other intangibles in progress',
      '2211': 'Agricultural operational land',
      '2212': 'Forestry operational land',
      '2218': 'Other agricultural/forestry land',
      '2221': 'Building plots (land for development)',
      '2228': 'Other undeveloped land',
      '2231': 'Land for industrial and agricultural buildings',
      '2232': 'Land for administrative and commercial buildings',
      '2234': 'Land for other professional use buildings',
      '2235': 'Land for non-professional use buildings',
      '2238': 'Other land with buildings',
      '2241': 'Tree and shrub planting works',
      '2248': 'Other land development works',
      '2251': 'Quarries',
      '2261': 'Car park land',
      '2281': 'Land for rental property buildings',
      '2285': 'Land for staff accommodation',
      '2288': 'Other miscellaneous land',
      '2291': 'Agricultural/forestry land improvements in progress',
      '2292': 'Bare land improvements in progress',
      '2295': 'Mineral land improvements in progress',
      '2298': 'Other land improvements in progress',
      '2311': 'Industrial buildings (own land)',
      '2312': 'Agricultural buildings (own land)',
      '2313': 'Administrative and commercial buildings (own land)',
      '2314': 'Staff accommodation buildings (own land)',
      '2315': 'Rental investment property buildings (own land)',
      '2321': 'Industrial buildings (third-party land)',
      '2322': 'Agricultural buildings (third-party land)',
      '2323': 'Administrative and commercial buildings (third-party land)',
      '2324': 'Staff accommodation buildings (third-party land)',
      '2325': 'Rental investment property buildings (third-party land)',
      '2331': 'Roads and earthworks',
      '2332': 'Railway infrastructure',
      '2333': 'Waterways',
      '2334': 'Dams and dikes',
      '2335': 'Airfield runways and taxiways',
      '2338': 'Other infrastructure works',
      '2341': 'Specialised complex installations on own land',
      '2342': 'Specialised complex installations on third-party land',
      '2343': 'Specific installations on own land',
      '2344': 'Specific installations on third-party land',
      '2351': 'General office installations',
      '2358': 'Other office fittings',
      '2411': 'Industrial machinery',
      '2412': 'Industrial tools',
      '2413': 'Commercial equipment',
      '2414': 'Commercial tools',
      '2421': 'Agricultural machinery',
      '2422': 'Agricultural tools',
      '2441': 'Office equipment',
      '2442': 'Computer hardware and IT equipment',
      '2443': 'Office machines (printers, copiers, etc.)',
      '2444': 'Office furniture',
      '2446': 'Equipment and furniture in rental/investment buildings',
      '2447': 'Equipment and furniture in staff accommodation',
      '2451': 'Motor vehicles',
      '2452': 'Railway rolling stock',
      '2453': 'River and lagoon watercraft',
      '2454': 'Sea-going vessels',
      '2455': 'Aircraft',
      '2456': 'Horse-drawn vehicles',
      '2458': 'Other transport (bicycle, moped, motorcycle)',
      '2461': 'Draft animals / livestock (working animals)',
      '2462': 'Breeding livestock',
      '2463': 'Guard animals',
      '2465': 'Perennial agricultural plantations',
      '2468': 'Other biological assets',
      '2481': 'Collections and works of art',
      '2491': 'Industrial and commercial equipment in progress',
      '2492': 'Agricultural equipment in progress',
      '2493': 'Returnable packaging equipment in progress',
      '2494': 'Office equipment and furniture in progress',
      '2495': 'Transport equipment in progress',
      '2496': 'Biological assets in progress',
      '2497': 'Equipment fittings in progress',
      '2498': 'Other equipment in progress',
      '2711': 'Participating loans granted',
      '2712': 'Loans to shareholders/partners',
      '2713': 'Business purchase notes receivable',
      '2714': 'Securities lent to third parties',
      '2721': 'Housing loans to employees',
      '2722': 'Equipment and installation loans to employees',
      '2728': 'Other loans to employees (education, etc.)',
      '2731': 'Performance bond retentions receivable from the State',
      '2733': 'Regulated fund receivable',
      '2738': 'Other receivables from the State',
      '2741': 'Portfolio investment securities (TIAP)',
      '2742': 'Participating securities (non-voting bonds)',
      '2743': 'Investment certificates',
      '2744': 'Mutual fund units (FCP)',
      '2748': 'Other long-term investment securities',
      '2751': 'Rental deposits paid',
      '2752': 'Electricity deposits paid',
      '2753': 'Water deposits paid',
      '2754': 'Gas deposits paid',
      '2755': 'Telephone and telecoms deposits paid',
      '2756': 'Public contract sureties paid',
      '2757': 'Other sureties paid',
      '2758': 'Other deposits and sureties paid',
      '2761': 'Accrued interest on non-trade loans',
      '2762': 'Accrued interest on employee loans',
      '2763': 'Accrued interest on State receivables',
      '2764': 'Accrued interest on long-term securities',
      '2765': 'Accrued interest on deposits paid',
      '2767': 'Accrued interest on participation-related receivables',
      '2768': 'Accrued interest on other long-term financial assets',
      '2771': 'Intra-group participation receivables',
      '2772': 'Non-group participation receivables',
      '2773': 'Receivables from joint venture entities',
      '2774': 'Advances to Economic Interest Groups',
      '2781': 'Miscellaneous intra-group receivables',
      '2782': 'Miscellaneous non-group receivables',
      '2785': 'Gold and precious metals held as financial assets',
      '2811': 'Depreciation — R&D costs',
      '2812': 'Depreciation — patents, licences and similar rights',
      '2813': 'Depreciation — software',
      '2814': 'Depreciation — trademarks',
      '2815': 'Amortisation — goodwill',
      '2816': 'Amortisation — leasehold rights',
      '2817': 'Depreciation — creative investments',
      '2818': 'Depreciation — other intangibles',
      '2821': 'Depreciation — agricultural/forestry land',
      '2824': 'Depreciation — land development works',
      '2825': 'Depreciation — mineral/quarry land',
      '2831': 'Depreciation — buildings on own land',
      '2832': 'Depreciation — buildings on third-party land',
      '2833': 'Depreciation — infrastructure works',
      '2834': 'Depreciation — technical installations',
      '2835': 'Depreciation — office fittings',
      '2837': 'Depreciation — concession buildings',
      '2838': 'Depreciation — other installations and fittings',
      '2841': 'Depreciation — industrial and commercial equipment',
      '2842': 'Depreciation — agricultural equipment',
      '2843': 'Depreciation — returnable packaging',
      '2844': 'Depreciation — office equipment and furniture',
      '2845': 'Depreciation — vehicles and transport equipment',
      '2846': 'Depreciation — biological assets',
      '2847': 'Depreciation — equipment fittings',
      '2848': 'Depreciation — other equipment',
      '2912': 'Impairment — patents and licences',
      '2913': 'Impairment — software',
      '2914': 'Impairment — trademarks',
      '2915': 'Impairment — goodwill',
      '2916': 'Impairment — leasehold rights',
      '2917': 'Impairment — creative investments',
      '2918': 'Impairment — other intangibles',
      '2919': 'Impairment — intangibles under development',
      '2921': 'Impairment — agricultural/forestry land',
      '2922': 'Impairment — undeveloped land',
      '2923': 'Impairment — land with buildings',
      '2924': 'Impairment — land development works',
      '2925': 'Impairment — mineral/quarry land',
      '2926': 'Impairment — improved land',
      '2927': 'Impairment — concession land',
      '2928': 'Impairment — other land',
      '2929': 'Impairment — land improvements in progress',
      '2931': 'Impairment — buildings on own land',
      '2932': 'Impairment — buildings on third-party land',
      '2933': 'Impairment — infrastructure works',
      '2934': 'Impairment — technical installations',
      '2935': 'Impairment — office fittings',
      '2937': 'Impairment — concession buildings',
      '2938': 'Impairment — other installations',
      '2939': 'Impairment — buildings under construction',
      '2941': 'Impairment — industrial equipment',
      '2942': 'Impairment — agricultural equipment',
      '2943': 'Impairment — returnable packaging',
      '2944': 'Impairment — office equipment and furniture',
      '2945': 'Impairment — transport equipment',
      '2946': 'Impairment — biological assets',
      '2947': 'Impairment — equipment fittings',
      '2948': 'Impairment — other equipment',
      '2949': 'Impairment — equipment under acquisition',
      '2951': 'Impairment — advances on intangibles',
      '2952': 'Impairment — advances on tangibles',
      '2961': 'Impairment — subsidiary investments',
      '2962': 'Impairment — joint venture investments',
      '2963': 'Impairment — associate investments',
      '2965': 'Impairment — professional organisation interests',
      '2966': 'Impairment — GIE interests',
      '2968': 'Impairment — other equity investments',
      '2971': 'Impairment — non-trade loans',
      '2972': 'Impairment — employee loans',
      '2973': 'Impairment — State receivables',
      '2974': 'Impairment — long-term securities',
      '2975': 'Impairment — deposits paid',
      '2977': 'Impairment — participation receivables',
      '2978': 'Impairment — miscellaneous financial receivables',
      '3111': 'Merchandise A — subcategory 1',
      '3112': 'Merchandise A — subcategory 2',
      '3121': 'Merchandise B — subcategory 1',
      '3122': 'Merchandise B — subcategory 2',
      '3351': 'Non-returnable packaging',
      '3352': 'Returnable non-individually-identifiable packaging',
      '3353': 'Mixed-use packaging',
      '3358': 'Other packaging materials',
      '3411': 'Products in progress — type P1',
      '3412': 'Products in progress — type P2',
      '3421': 'Works in progress — type T1',
      '3422': 'Works in progress — type T2',
      '3431': 'Semi-finished products A in progress',
      '3432': 'Semi-finished products B in progress',
      '3441': 'By-products A in progress',
      '3442': 'By-products B in progress',
      '3511': 'Studies in progress — type E1',
      '3512': 'Studies in progress — type E2',
      '3521': 'Services in progress — type S1',
      '3522': 'Services in progress — type S2',
      '3711': 'Intermediate products — category A',
      '3712': 'Intermediate products — category B',
      '3721': 'Waste materials',
      '3722': 'Scrap / rejects',
      '3723': 'Recovered / recycled materials',
      '3871': 'Stock held on consignment',
      '3872': 'Stock held in storage',
      '4011': 'Trade suppliers',
      '4012': 'Intra-group suppliers',
      '4013': 'Subcontractor suppliers',
      '4017': 'Supplier — performance bond retentions',
      '4021': 'Trade supplier bills payable',
      '4022': 'Intra-group supplier bills payable',
      '4023': 'Subcontractor bills payable',
      '4081': 'Accrued trade supplier payables',
      '4082': 'Accrued intra-group supplier payables',
      '4083': 'Accrued subcontractor payables',
      '4086': 'Accrued interest on supplier payables',
      '4091': 'Advances and deposits paid to suppliers',
      '4092': 'Advances paid to group suppliers',
      '4093': 'Advances paid to subcontractors',
      '4094':
        'Claims on suppliers for packaging and equipment to be returned',
      '4098':
        'Rebates, discounts and other credits to be received from suppliers',
      '4111': 'Trade customers',
      '4112': 'Intra-group customers',
      '4114': 'Public-sector customers (State and local authorities)',
      '4115': 'International organisation customers',
      '4117': 'Customer — performance bond retentions receivable',
      '4118': 'Customers — VAT rebates receivable',
      '4121': 'Trade customer bills receivable',
      '4122': 'Intra-group customer bills receivable',
      '4124': 'Public authority bills receivable',
      '4125': 'International organisation bills receivable',
      '4141': 'Asset disposal receivables — open account',
      '4142': 'Asset disposal receivables — bills receivable',
      '4161': 'Disputed customer receivables',
      '4162': 'Doubtful / impaired customer receivables',
      '4181': 'Accrued customer revenue — invoices to be issued',
      '4186': 'Accrued interest on customer receivables',
      '4191': 'Advances and deposits received from customers',
      '4192': 'Advances received from group customers',
      '4194':
        'Liabilities to customers for consigned packaging and equipment',
      '4198': 'Rebates and credits to be granted to customers',
      '4211': 'Advances to employees',
      '4212': 'Salary advances (partial payments)',
      '4213': 'Expenses paid and goods supplied to employees',
      '4231': 'Wage oppositions / freezes',
      '4232': 'Wage garnishments',
      '4233': 'Third-party holder notices on wages',
      '4241': 'Company medical assistance',
      '4242': 'Family allowances',
      '4245': 'Company-affiliated social organisations',
      '4248': 'Other internal employee welfare programs',
      '4251': 'Employee delegates',
      '4252': 'Trade unions and works councils',
      '4258': 'Other employee representatives',
      '4281': 'Accrued holiday/leave pay liability',
      '4286': 'Other accrued employee charges',
      '4287': 'Employee-related income accruals',
      '4311': 'Family benefit contributions',
      '4312': 'Workplace accident contributions',
      '4313': 'Mandatory pension fund contributions',
      '4314': 'Optional pension fund contributions',
      '4318': 'Other social security contributions',
      '4331': 'Mutual insurance fund contributions',
      '4334': 'Output VAT on self-supply',
      '4335': 'Output VAT on accrued revenue (invoices to be issued)',
      '4381': 'Social charges on accrued bonuses',
      '4382': 'Social charges on accrued leave pay',
      '4386': 'Other accrued social charges',
      '4387': 'Social organisation income receivable',
      '4421': 'State taxes and duties',
      '4422': 'Local authority taxes and duties',
      '4423': 'Taxes recoverable on bondholders',
      '4424': 'Taxes recoverable on shareholders',
      '4426': 'Customs duties',
      '4428': 'Other taxes and duties',
      '4431': 'Output VAT on sales of goods',
      '4432': 'Output VAT on services rendered',
      '4433': 'Output VAT on construction works',
      '4441': 'VAT payable to the State (net VAT liability)',
      '4449': 'VAT credit to be carried forward (recoverable)',
      '4451': 'Input VAT on fixed asset purchases',
      '4452': 'Input VAT on stock and supply purchases',
      '4453': 'Input VAT on transport services',
      '4454': 'Input VAT on external services and other charges',
      '4455': 'Input VAT on uninvoiced purchases',
      '4456': 'VAT transferred from other companies',
      '4471': 'General income tax withheld',
      '4472': 'Payroll taxes withheld',
      '4473': 'National contribution withheld',
      '4474': 'National solidarity contribution withheld',
      '4478': 'Other withholding taxes and contributions',
      '4486': 'Accrued tax charges',
      '4487': 'Tax refunds receivable',
      '4491': 'State — secured tax obligations (guaranteed payments)',
      '4492': 'Tax advances and prepayments made',
      '4493': 'State endowment funds receivable',
      '4494': 'Equipment grants receivable from the State',
      '4495': 'Operating grants receivable from the State',
      '4496': 'Balancing grants receivable from the State',
      '4499': 'State — regulated fund provisioned',
      '4581':
        'Endowment funds receivable from international organisations',
      '4582': 'Grants receivable from international organisations',
      '4611': 'Shareholders — contributions in kind',
      '4612': 'Shareholders — cash contributions',
      '4613': 'Shareholders — called but unpaid capital',
      '4614': 'Partners — called but unpaid capital',
      '4615': 'Shareholders — payments received on capital increase',
      '4616': 'Shareholders — advance payments',
      '4617': 'Defaulting shareholders',
      '4618': 'Partners — other contributions',
      '4619': 'Shareholders — capital to be reimbursed',
      '4621': 'Partner current account — principal',
      '4626': 'Accrued interest on partner current accounts',
      '4711': 'Miscellaneous debtors — suspense',
      '4712': 'Miscellaneous creditors — suspense',
      '4726': 'Unpaid calls on equity investments',
      '4727': 'Unpaid calls on long-term securities',
      '4728': 'Unpaid calls on short-term investment securities',
      '4746': 'Periodic expense allocation',
      '4747': 'Periodic income allocation',
      '4781':
        'Decrease in foreign-currency receivables due to exchange rate movement',
      '4782':
        'Increase in foreign-currency payables due to exchange rate movement',
      '4788': 'Translation differences offset by hedging',
      '4791':
        'Increase in foreign-currency receivables due to exchange rate movement',
      '4792':
        'Decrease in foreign-currency payables due to exchange rate movement',
      '4798': 'Translation gains offset by hedging',
      '4811': 'Payables for intangible assets purchased',
      '4812': 'Payables for tangible assets purchased',
      '4817': 'Performance bond retentions — investment suppliers',
      '4818': 'Uninvoiced capital expenditure payables',
      '4851': 'Asset disposal receivables — open account',
      '4852': 'Asset disposal receivables — bills receivable',
      '4857': 'Performance bond retentions on asset disposals',
      '4858': 'Asset disposal receivables — invoices to be issued',
      '4911': 'Impairment — disputed receivables',
      '4912': 'Impairment — doubtful receivables',
      '4962': 'Impairment on partner current accounts',
      '4963': 'Impairment on joint venture transactions',
      '4966': 'Impairment on group current accounts',
      '4981': 'Impairment on asset disposal receivables',
      '4982': 'Impairment on investment security disposal receivables',
      '4983': 'Impairment on other non-ordinary receivables',
      '4991': 'Short-term provisions for operating risks',
      '4998': 'Short-term provisions for non-ordinary activity risks',
      '5011': 'Short-term Treasury bills',
      '5012': 'Financial institution short-term securities',
      '5013': 'Short-term cash vouchers / certificates',
      '5021': 'Own shares (treasury shares)',
      '5022': 'Listed shares held for trading',
      '5023': 'Unlisted shares held for trading',
      '5024': 'Split shares — investment certificates and voting rights',
      '5025': 'Other equity-type securities',
      '5031': 'Own bonds repurchased by the company',
      '5032': 'Listed bonds held for trading',
      '5033': 'Unlisted bonds held for trading',
      '5035': 'Other debt securities held for trading',
      '5042': 'Share subscription warrants',
      '5043': 'Bond subscription warrants',
      '5061': 'Accrued interest on Treasury bills',
      '5062': 'Accrued dividends on shares',
      '5063': 'Accrued interest on bonds',
      '5181': 'Warrants pending collection',
      '5182': 'Business purchase notes receivable pending collection',
      '5185': 'Travellers cheques pending encashment',
      '5186': 'Matured coupons pending encashment',
      '5187': 'Matured bond interest coupons pending encashment',
      '5211': 'Bank account — Bank X (placeholder for actual bank name)',
      '5212': 'Bank account — Bank Y (placeholder for actual bank name)',
      '5711': 'Head office cash — local currency',
      '5712': 'Head office cash — foreign currency',
      '5721': 'Branch A cash — local currency',
      '5722': 'Branch A cash — foreign currency',
      '5731': 'Branch B cash — local currency',
      '5732': 'Branch B cash — foreign currency',
      '6011': 'Merchandise purchases within the UEMOA region',
      '6012': 'Merchandise purchases outside the UEMOA region',
      '6013': 'Intra-group merchandise purchases within the region',
      '6014': 'Intra-group merchandise purchases outside the region',
      '6019':
        'Purchase rebates and discounts on merchandise (unallocated)',
      '6021': 'Raw material purchases within the UEMOA region',
      '6022': 'Raw material purchases outside the UEMOA region',
      '6023': 'Intra-group raw material purchases within the region',
      '6024': 'Intra-group raw material purchases outside the region',
      '6029':
        'Purchase rebates and discounts on raw materials (unallocated)',
      '6031': 'Change in merchandise inventory',
      '6032': 'Change in raw material inventory',
      '6033': 'Change in other supply inventory',
      '6041': 'Consumable materials purchased',
      '6042': 'Fuel and combustible materials purchased',
      '6043': 'Cleaning and maintenance products purchased',
      '6044': 'Workshop and factory supplies purchased',
      '6046': 'Store/warehouse supplies purchased',
      '6047': 'Office supplies purchased',
      '6049': 'Purchase rebates on consumables (unallocated)',
      '6051': 'Non-stock supplies — water',
      '6052': 'Non-stock supplies — electricity',
      '6053': 'Non-stock supplies — other energy sources',
      '6054': 'Non-stock maintenance supplies',
      '6055': 'Non-stock office supplies',
      '6056': 'Small equipment and tools purchased (expensed)',
      '6057': 'Purchases of studies and consulting services',
      '6058': 'Purchases of works, materials and equipment (expensed)',
      '6059': 'Purchase rebates on other purchases (unallocated)',
      '6081': 'Non-returnable packaging purchased',
      '6082': 'Returnable non-identifiable packaging purchased',
      '6083': 'Mixed-use packaging purchased',
      '6089': 'Purchase rebates on packaging (unallocated)',
      '6181': 'Business travel and travel expenses',
      '6182': 'Transfers between branches or construction sites',
      '6183': 'Administrative transport expenses',
      '6221': 'Land rental expenses',
      '6222': 'Building and premises rental expenses',
      '6223': 'Equipment and tool rental expenses',
      '6224': 'Losses on packaging (unreturned packaging cost)',
      '6225': 'Packaging rental charges',
      '6228': 'Miscellaneous rental and occupancy charges',
      '6232': 'Real estate finance lease payments',
      '6233': 'Movable asset finance lease payments',
      '6235': 'Other similar contract payments',
      '6241': 'Real estate maintenance and repairs',
      '6242': 'Movable asset maintenance and repairs',
      '6243': 'Maintenance contracts and services',
      '6248': 'Other maintenance and repair costs',
      '6251': 'Multi-risk (comprehensive) insurance premiums',
      '6252': 'Vehicle insurance premiums',
      '6253': 'Business risk insurance premiums',
      '6254': 'Product liability insurance premiums',
      '6255': 'Trade credit / bad debt insurance premiums',
      '6256': 'Inbound transport insurance premiums',
      '6257': 'Outbound transport insurance premiums',
      '6258': 'Other insurance premiums',
      '6261': 'Research and feasibility study costs',
      '6265': 'General documentation and library costs',
      '6266': 'Technical documentation costs',
      '6271': 'Advertising placements and insertions',
      '6272': 'Catalogues and promotional printed materials',
      '6273': 'Product samples',
      '6274': 'Trade fairs and exhibitions',
      '6275': 'Publications expenses',
      '6276': 'Client gifts',
      '6277': 'Conference, seminar and symposium costs',
      '6278': 'Other advertising and PR expenses',
      '6281': 'Telephone expenses',
      '6282': 'Telex expenses',
      '6283': 'Fax expenses',
      '6288': 'Other telecommunications expenses',
      '6311': 'Securities transaction fees (buy, sell, custody)',
      '6312': 'Bill of exchange handling charges',
      '6313': 'Safe deposit box rental',
      '6315': 'Credit card commission charges',
      '6316': 'Bond issuance fees',
      '6318': 'Other bank charges',
      '6321': 'Commission and brokerage on purchases',
      '6322': 'Commission and brokerage on sales',
      '6323': 'Freight forwarder and customs agent fees',
      '6324': 'Professional fees (lawyers, accountants, etc.)',
      '6325': 'Legal document and litigation costs',
      '6328': 'Miscellaneous intermediary fees',
      '6342': 'Royalties for patents, licences and concessions',
      '6343': 'Software licence fees and royalties',
      '6344': 'Trademark royalties',
      '6351': 'Professional association membership dues',
      '6358': 'Various other contributions',
      '6371': 'Temporary / agency staff costs',
      '6372': 'Seconded or loaned staff costs',
      '6381': 'Staff recruitment costs',
      '6382': 'Removal and relocation costs',
      '6383': 'Entertainment and reception expenses',
      '6384': 'Business mission and assignment expenses',
      '6411': 'Property taxes and related levies',
      '6412': 'Business licences (patente) and related taxes',
      '6413': 'Payroll and salary taxes',
      '6414': 'Apprenticeship levy',
      '6415': 'Continuing professional training levy',
      '6418': 'Other direct taxes',
      '6461': 'Transfer / conveyance duties',
      '6462': 'Stamp duties',
      '6463': 'Company vehicle tax',
      '6464': 'Vehicle registration stickers / road tax',
      '6468': 'Other registration duties',
      '6471': 'Assessment penalties — direct taxes',
      '6472': 'Assessment penalties — indirect taxes',
      '6473': 'Collection penalties — direct taxes',
      '6474': 'Collection penalties — indirect taxes',
      '6478': 'Other tax and criminal fines',
      '6511': 'Write-off of irrecoverable customer receivables',
      '6515': 'Write-off of irrecoverable other receivables',
      '6521': 'Share of profits transferred — manager accounting',
      '6525':
        'Losses allocated by transfer — non-managing partners accounting',
      '6581': 'Directors fees and other board remuneration',
      '6582': 'Charitable donations',
      '6583': 'Corporate sponsorship and patronage',
      '6591': 'Short-term operating risk provisions charged',
      '6593': 'Stock impairment provisions charged',
      '6594': 'Receivable impairment provisions charged',
      '6598': 'Other provisions charged',
      '6611': 'Salaries, wages and commissions — national staff',
      '6612': 'Bonuses and performance awards — national staff',
      '6613': 'Paid leave — national staff',
      '6614':
        'Notice, redundancy and job-search allowances — national staff',
      '6615': 'Sickness allowances paid — national staff',
      '6616': 'Family supplement allowance — national staff',
      '6617': 'Benefits in kind — national staff',
      '6618': 'Other direct remuneration — national staff',
      '6621': 'Salaries, wages and commissions — expatriate staff',
      '6622': 'Bonuses and performance awards — expatriate staff',
      '6623': 'Paid leave — expatriate staff',
      '6624':
        'Notice, redundancy and job-search allowances — expatriate staff',
      '6625': 'Sickness allowances paid — expatriate staff',
      '6626': 'Family supplement allowance — expatriate staff',
      '6627': 'Benefits in kind — expatriate staff',
      '6628': 'Other direct remuneration — expatriate staff',
      '6631': 'Housing allowances',
      '6632': 'Representation / entertainment allowances',
      '6633': 'Expatriation allowances',
      '6638': 'Other allowances and benefits',
      '6641': 'Social charges on national staff remuneration',
      '6642': 'Social charges on expatriate staff remuneration',
      '6661': "Sole trader's notional labour remuneration",
      '6662': "Sole trader's social charges",
      '6671': 'Temporary staff cost transferred',
      '6672': 'Seconded staff cost transferred',
      '6681': 'Payments to trade unions and works councils',
      '6682': 'Payments to health and safety committees',
      '6683': 'Payments to other social welfare programs',
      '6684': 'Occupational health and pharmacy costs',
      '6711': 'Interest on bond loans',
      '6712': 'Interest on bank loans',
      '6713': 'Interest on participation-related debts',
      '6721': 'Finance charges in real estate lease rentals',
      '6722': 'Finance charges in movable asset lease rentals',
      '6723': 'Finance charges in other lease rentals',
      '6741': 'Interest on advances received and credit deposits',
      '6742': 'Interest on blocked current accounts',
      '6743': 'Interest on guaranteed/secured debt obligations',
      '6744': 'Late payment interest on trade payables',
      '6745': 'Bank interest and treasury/discounting charges',
      '6748': 'Interest on miscellaneous debts',
      '6781': 'Losses on life annuity financial risks',
      '6782': 'Losses on financial operations',
      '6784': 'Losses on treasury/derivative instruments',
      '6791': 'Provisions for financial risks charged',
      '6795': 'Provisions for investment securities impairment charged',
      '6798': 'Other financial provisions charged',
      '6811': 'Amortisation of deferred charges',
      '6812': 'Amortisation of intangible assets',
      '6813': 'Depreciation of tangible fixed assets',
      '6872': 'Amortisation of bond redemption premiums',
      '6878': 'Other financial amortisation charges',
      '6911': 'Operating provisions for risks and charges',
      '6912': 'Provisions for major repairs',
      '6913': 'Impairment provisions on intangible assets',
      '6914': 'Impairment provisions on tangible assets',
      '6971': 'Financial provisions for risks and charges',
      '6972': 'Impairment provisions on financial assets',
      '7011': 'Merchandise sales within the UEMOA region',
      '7012': 'Merchandise sales outside the UEMOA region',
      '7013': 'Intra-group merchandise sales within the region',
      '7014': 'Intra-group merchandise sales outside the region',
      '7021': 'Finished goods sales within the UEMOA region',
      '7022': 'Finished goods sales outside the UEMOA region',
      '7023': 'Intra-group finished goods sales within the region',
      '7024': 'Intra-group finished goods sales outside the region',
      '7031': 'Intermediate product sales within the UEMOA region',
      '7032': 'Intermediate product sales outside the UEMOA region',
      '7033': 'Intra-group intermediate product sales within the region',
      '7034': 'Intra-group intermediate product sales outside the region',
      '7041': 'By-product sales within the UEMOA region',
      '7042': 'By-product sales outside the UEMOA region',
      '7043': 'Intra-group by-product sales within the region',
      '7044': 'Intra-group by-product sales outside the region',
      '7051': 'Billed works within the UEMOA region',
      '7052': 'Billed works outside the UEMOA region',
      '7053': 'Intra-group billed works within the region',
      '7054': 'Intra-group billed works outside the region',
      '7061': 'Services sold within the UEMOA region',
      '7062': 'Services sold outside the UEMOA region',
      '7063': 'Intra-group services sold within the region',
      '7064': 'Intra-group services sold outside the region',
      '7071': 'Freight and non-returnable packaging billed to customers',
      '7072': 'Commissions and brokerage income',
      '7073': 'Rental income',
      '7074': 'Surplus on return and sale of packaging',
      '7075': 'Staff secondment income',
      '7076':
        'Royalty income from patents, software, trademarks and similar',
      '7077':
        'Services operated for the benefit of employees (charged back)',
      '7078': 'Other ancillary income',
      '7181': 'Operating grants from the State and public authorities',
      '7182': 'Operating grants from international organisations',
      '7183': 'Operating grants from other third parties',
      '7341': 'Change in manufactured products in progress',
      '7342': 'Change in works in progress',
      '7351': 'Change in studies in progress',
      '7352': 'Change in service contracts in progress',
      '7371': 'Change in intermediate products inventory',
      '7372': 'Change in by-products and waste inventory',
      '7521': 'Share of losses transferred — manager accounting',
      '7525':
        'Profits allocated by transfer — non-managing partner accounting',
      '7581': "Directors' fees received (income side)",
      '7582': 'Insurance indemnities received',
      '7591': 'Reversal of short-term operating risk provisions',
      '7593': 'Reversal of stock impairment provisions',
      '7594': 'Reversal of receivable impairment provisions',
      '7598': 'Reversal of other operating provisions',
      '7781': 'Gains on life annuity financial risks',
      '7782': 'Gains on financial operations',
      '7784': 'Gains on treasury/derivative instruments',
      '7791': 'Reversal of financial risk provisions',
      '7795': 'Reversal of investment security impairment provisions',
      '7798': 'Reversal of other financial provisions',
      '7911': 'Reversal of operating provisions for risks and charges',
      '7912': 'Reversal of major repair provisions',
      '7913': 'Reversal of intangible asset impairment provisions',
      '7914': 'Reversal of tangible asset impairment provisions',
      '7971': 'Reversal of financial provisions for risks and charges',
      '7972': 'Reversal of financial asset impairment provisions',
      '8911': 'Income tax on activities in the home State',
      '8912': 'Income tax on activities in other UEMOA member states',
      '8913': 'Income tax on activities outside the UEMOA region',
      '8991': 'Tax rebates and reductions on prior year taxes',
      '8994': 'Tax annulments due to retroactive losses',
      '9011': 'Confirmed credit lines obtained',
      '9012': 'Loan drawdowns remaining to be received',
      '9013': 'Revolving financing facilities obtained',
      '9014': 'Note issuance facilities obtained',
      '9018': 'Other financing commitments obtained',
      '9021': 'Endorsements received',
      '9022': 'Sureties and guarantees received',
      '9023': 'Mortgages received as collateral',
      '9024': 'Bills endorsed by third parties (in our favour)',
      '9028': 'Other guarantees received',
      '9031': 'Forward purchase commitments for merchandise',
      '9032': 'Forward currency purchase commitments',
      '9033': 'Firm customer purchase orders received',
      '9038': 'Other reciprocal commitments obtained',
      '9041': 'Conditional debt waivers obtained',
      '9043': 'Sales with retention of title clause (seller perspective)',
      '9048': 'Various other commitments obtained',
      '9051': 'Credit lines granted but not yet drawn down',
      '9058': 'Other financing commitments granted',
      '9061': 'Endorsements given',
      '9062': 'Sureties and guarantees given',
      '9063': 'Mortgages given as collateral',
      '9064': 'Bills endorsed by the company (in favour of third parties)',
      '9068': 'Other guarantees given',
      '9071': 'Forward sale commitments for merchandise',
      '9072': 'Forward currency sale commitments',
      '9073': 'Firm purchase orders placed with suppliers',
      '9078': 'Other reciprocal commitments given',
      '9081': 'Conditional debt cancellations granted',
      '9082': 'Pension and retirement commitments',
      '9083':
        'Purchases with retention of title clause (buyer perspective)',
      '9088': 'Various other commitments given',
    }),
    'en',
  );

  test('#01 => Account "10"', () => {
    expect(i18n.translate('10').to('en')).toBe(
      'Capital — overall grouping of all capital accounts',
    );
  });
});
